#!/bin/bash
# Write a shell script that adds the two numbers stored in the environment variables WATER and STIR and prints the result.
# WATER is in base water
# STIR is in base stir.
# The result should be in base bestchol 
echo $(( 2#$(echo "$WATER" | tr 'water' '01234') + 2#$(echo "$STIR" | tr 'stir.' '01234') )) | tr '0123456789' 'bestcholhc'


